= 项目接口设计实践
杨晓辰
2019-07-25
:toc: left
:toclevels: 4
:icons: font
:sectnums:
:jbake-type: post
:jbake-tags: code_and_think, java, api
:jbake-status: published

== 前言

项目不同, 项目提供的接口功能也不同, 能否有一套比较通用切良好的规则, 来指导我们对项目接口的宏观设计和细节设计? 

本文是我在项目中设计 api 接口的一些实践经验.

== 接口
=== 宏观战略
==== 接口组织结构

一个项目中, 接口组织结构应该是良好干净的. 接口不是想写哪里写哪里, 接口需要有功能分类, 业务分类, 协议分类, 然后分门别类的组织在不同的文件夹里.

按照功能作用分::
* 系统间服务接口
* 前端接口  

按照业务分::
* 业务模块 A
* 业务模块 B

按照协议分::
* dubbo
* http

很多人多多少少想过这些分类, 但很少想过要把接口按照这些组织好. 我给出一个接口的组织目录

[source,java]
----
application 
+-- api                         // 面向服务的接口
|   +-- dubbo                   // dubbo 协议的接口
|   |   +-- order               // 按照业务化分, order 模块的接口
|   |   +-- product
|   |   \-- module C
|   \-- http                    // http 协议的接口
+-- controller                  // 面向前端的接口
|   +-- web                     // ajax 请求接口
|   |   +-- order               // 按照业务化分
|   |   \-- product 
|   +-- page                    // 页面请求接口
|   +-- manage                  // 管理用的 ajax 和 页面接口.
|       +-- web
|       \-- page
\-- callback                    // 接收回调的接口
----

* 首先按照面向服务, 面向前端进行化分.

** 验证方式不同. 面向前端的接口通常要认证登录状态; 面向服务的接口通常是接入验证.
** 使用者不同. 前端接口调用者是用户, 请求的数据通常更贴近展示, 面向展示设计接口, 当发生异常时, 需要返回一些用户可读的信息; 服务接口使用者是系统代码, 请求的数据更贴近领域模型, 根据自身领域来暴露服务, 发生异常时, 需要返回明确的状态码, 来供调用方程序判断.

* 在面向服务的接口中, 提供了不同协议的接口. 不同协议的接口中, 又按照不同的模块化分.
* 在面向前端的接口中, 分为 `web` 和 `page` 两种, 分别应对 ajax 请求和页面请求.
* 在面向前端的接口中, `manage` 包里为管理后台的接口. 因为管理后台通常跟前台的请求要求的身份权限不同.
* 独立出 `callback` 类型的接口, 这种接口往往按照回调发起方的接口规范来.

以上, 我们通过接口的受众和类型, 制定了一套接口的组织形式. 

目的是保持清晰, 避免混用. 因为我们经常会在接口层做一些通用的操作, 比如日志, 性能打点, 认证等, 对于不同的功能和作用的接口是不同的, 做划分之后, 我们可以分别处理.

上面的目录划分的真实代码示例, 可以在 https://github.com/yxc023/blueprint/tree/master/blueprint-application/src/main/java/com/yangxiaochen/blueprint[blueprint project] 找到.

=== 细节战术
== 文档
``