= Gradle多模块项目中的配置实践
杨晓辰
2022-05-04
:toc: top
:toclevels: 5
:icons: font
// :sectnums:
:jbake-type: post
:jbake-tags: gradle, build.gradle, 多模块项目构建
:jbake-status: published
:description: 使用 Gradle 在多模块项目中的配置实践。Gradle 脚本文件的原理，如何理解 gradle 构建脚本，build.gradle 文件中有什么内容

== 前言
Gradle 是一个第一眼看上去比较简单，但是有一定入门门槛的构建工具。

配置仓库、引入依赖这种基本配置，是比较简单的，也有很多例子。

但是想做一些其他的个性化配置，经常无处下手。官方文档，虽然很详实，但是对于没有进行系统学习的人，看起来还挺费劲。而且，文档中给出的例子，跟实际情况脱离较远，不是很好参照。

Gradle 的配置文件，大多使用 groovy 来进行书写，弱类型的语言、dsl、closures 的表达方式，都会让很多 java 程序员摸不着头脑。说是用代码来做的配置，但是这种语法缺读不明白。

Gradle 简单明了的配置语法、极度灵活的自定义构建配置，是我一直使用它的原因。过程中也遇到了不少问题，虽然我没有对 Gradle 进行特别系统的学习，但也翻过不少文档和源码。

本篇文章，是对 Gradle 使用的一些实践记录。

== 一个多模块项目的构建脚本例子
这些文件来自项目： https://github.com/yxc023/gradle-practice

----
gradle-practice
├── build.gradle
├── gp-api
│   ├── build.gradle
├── gp-app
│   ├── build.gradle
├── gp-db
│   ├── build.gradle
├── gp-service
│   ├── build.gradle
├── gradle
│   ├── jooq.gradle
│   ├── publish.gradle
│   └── wrapper
├── gradlew
├── gradlew.bat
└── settings.gradle
----


.settings.gradle
[source,groovy]
----
// config plugin repositories
pluginManagement {
    repositories {
        // aliyun repository for gradle plugin
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        // default repository
        gradlePluginPortal()
    }
}

// set projects, root dir is root project. Each module is a sub project
rootProject.name = 'gradle-practice'

// include all sub projects. The name is location of the new project in the project hierarchy, for example 'a:b:c', not the file path
// Sub project's default path is the '${rootDir}/${projectName}'.
include 'gp-app'
// use ':' as a separator of project.
include 'gp-api'
include 'gpService'
include 'gp-db'

// Set a custom path for a project
project(':gpService').projectDir = new File(settingsDir, 'gp-service')
----
`settings.gradle` 中定义所有的项目

.build.gradle
[source,groovy]
----
/*
为构建脚本引入依赖。
在 「模块 gp-db」 中，我们使用了 jooq 生成代码的 plugin，所以，这里，会先把这个 plugin 的 library 引入进来
 */
buildscript {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/public' }
        mavenCentral()
    }
    dependencies {
        classpath 'nu.studer:gradle-jooq-plugin:4.2'
    }
}

/*
在多模块的项目中，根目录下的 build.gradle 文件，尽量把通用的全局配置都配置到这里

「project」是 gradle 里的核心概念。每个 module 都是一个 project，根目录下是 rootProject
 */
allprojects {
    // 定义所有项目的 group 和 version
    group = 'com.yangxiaochen.gradle.practice'
    version = '1.0.0-SNAPSHOT'

    // 为所有项目引入插件
    apply plugin: 'java'
    apply plugin: 'pmd'

    // 为所有项目
    repositories {
        maven { url 'https://maven.aliyun.com/repository/public' }
        mavenCentral()
    }

    // 定义一些变量
    ext {
        mysqlVersion = '8.0.18'
        jooqVersion = '3.13.1'
        jooqGenDataSourceDriver = 'com.mysql.jdbc.Driver'
        jooqGenDataSourceUrl = 'jdbc:mysql://127.0.0.1:3306/gp_database'
        jooqGenDataSourceUrlUser = 'gp_database_user'
        jooqGenDataSourceUrlPassword = 'test'
        jooqGenDataSourceInputSchema = 'gp_database'
    }

    // 为所有的项目设置依赖
    dependencies {
        pmd 'com.alibaba.p3c:p3c-pmd:1.3.6'
    }

    // Java compiler compile java source file with utf-8 (default gbk in the Windows OS with Simplified Chinese). Java source file must be 'UTF-8'.
    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
    }
    // Set java compile version
    sourceCompatibility = 1.8
    targetCompatibility = 1.8

    // pmd config
    pmd {
        consoleOutput = true
        reportsDir = file("build/reports/pmd")
        ruleSets = [
                'java-ali-comment',
                'java-ali-concurrent',
                'java-ali-constant',
                'java-ali-exception',
                'java-ali-flowcontrol',
                'java-ali-naming',
                'java-ali-oop',
                'java-ali-orm',
                'java-ali-other',
                'java-ali-set',
        ]
        ignoreFailures = true
    }
}

// Config for every subprojects
subprojects {
    // Project gp-api is a library, it will be published as a sdk lib. So it should define exact dependencies in project's build.gradle file
    // Define spring framework's core dependencies for most projects.
    if (!['gp-api'].contains(project.name)) {
        dependencies {


            // 'implementation platform' define Spring bom
            implementation platform('org.springframework.boot:spring-boot-dependencies:2.1.11.RELEASE')
            implementation platform('org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR3')

            // Spring framework core dependencies
            implementation("javax.annotation:javax.annotation-api")
            implementation("org.springframework:spring-context")
            implementation("org.springframework:spring-context-support")
            implementation("org.springframework:spring-tx")
            implementation 'org.springframework.boot:spring-boot-starter-freemarker'
            implementation 'org.aspectj:aspectjweaver'

            // Common utils dependencies
            compileOnly 'org.projectlombok:lombok:1.18.22'
            annotationProcessor 'org.projectlombok:lombok:1.18.22'
            implementation 'org.mapstruct:mapstruct:1.4.2.Final'
            annotationProcessor 'org.mapstruct:mapstruct-processor:1.4.2.Final'

            implementation 'org.slf4j:slf4j-api'
            implementation group: 'org.jodd', name: 'jodd-bean', version: '5.0.3'
            implementation group: 'org.apache.commons', name: 'commons-lang3'
            implementation 'com.google.guava:guava:28.2-jre'
        }
    }

    // Dependency resolve
    configurations {
        all {
            resolutionStrategy {
                force 'com.google.guava:guava:28.2-jre'
            }
            exclude group: 'org.slf4j', module: 'slf4j-log4j12'
            exclude group: 'org.mybatis.spring.boot'
        }
    }

}
----
这是一个多模块的项目，通过根项目下的 `build.gradle` 文件，做好全局配置，让每个子模块中的 `build.gradle` 足够简单。只需要配置额外的依赖即可，如

.gb-service/build.gradle
[source,groovy]
----
// 只需额外定义该模块所需的依赖
dependencies {
    implementation 'org.greenrobot:eventbus:3.1.1'
}
----

== 如何理解构建脚本

每一个 project 下都有一个名为 `build.gradle` 的构建脚本。

每一个 `build.gradle` 构建脚本背后，都隐含了一个 `Project` 对象。

这个构建脚本中定义的各种属性或者方法，基本都是这个 project 中包含的。比如你可以在脚本中直接使用 `Project` 接口中定义好的变量和方法。

project 中包含了这些重要的东西：

1. 自身的属性和方法
2. tasks - 当前 project 中包含的任务实例。引入一些 plugin 时，也会向 project 中添加 task
+
[source, groovy]
----
// 创建一个名字为 `jooqTask`，类型为 `JooqTask` 的 task
project.tasks.create("jooqTask", JooqTask.class)
----

3. extra property - 通过 ext block 声明的额外变量
+
[source, groovy]
----
ext {
    mysqlVersion = '8.0.18'
    jooqVersion = '3.13.1'
    jooqGenDataSourceDriver = 'com.mysql.jdbc.Driver'
    jooqGenDataSourceUrl = 'jdbc:mysql://127.0.0.1:3306/gp_database'
    jooqGenDataSourceUrlUser = 'gp_database_user'
    jooqGenDataSourceUrlPassword = 'test'
    jooqGenDataSourceInputSchema = 'gp_database'
}
----

4. extensions - 引入一些 plugin 时， 会向 project 中添加一些 extension 对象，并命名。
+
[source, groovy]
----
// 创建一个名字为 `$JOOQ_EXTENSION_NAME`，类型为 `JooqExtension` 的 extension。后面两个参数是 `JooqExtension` 的构造参数
project.extensions.create('jooq', JooqExtension.class, whenConfigurationAdded, 'jooq')
----
+
加入 extension 后，就可以在构建脚本中定义
+
[source]
----
jooq {
    version = jooqVersion
    edition = 'OSS'
    generateSchemaSourceOnCompilation = false
}
----

5. convention - 引入一些 plugin 时，会加入一些 convention object，翻译过来叫‘约定’，‘预定大于配置’的‘约定’。convention object 通常是 POJO，为 project 提供一些拓展属性。
+
[source, groovy]
----
// 这两个变量，在引入 java plugin 之后，就能在构建脚本里够直接定义下面的变量。
sourceCompatibility = 1.8
targetCompatibility = 1.8
----

总之，这些 project 中包含的重要信息的作用，它们定义了 `build.gradle` 中可以写什么 property 或者 block

当 `build.gradle` 中使用了一个 property 或者 block，他的查找顺序是：

1. 是否是 project 中的属性和方法
+
----
// version 这个变量，即是 project.version
version = '1.0.0'
----
2. 是否是 `ext` 定义的属性
3. 是否是 extensions 中的 extension 的名字
4. 是否是 convention 中定义的 pojo 中的变量
5. 是否是 task 的名字
6. 是否在上层 project 的 ext 和 convention 中
