= mkdir在/home目录下新建文件夹 for mac
杨晓辰
2016-03-31
// :toc: left
:toclevels: 4
:icons: font
:jbake-sid: create-dir-home-on-mac
:jbake-type: post
:jbake-tags: mac
:jbake-status: published

**这个文章比较老了, 针对最新的创建文件夹无权权限的问题**

**查看: link:/blog/mac/mkdir-read-only-file-system.html[苹果系统 macOS 创建文件夹遇到 Read-only file system 解决]**

----------------2020.03.27 更新----------------

Hmmm, trying to create a directory under '/home' on a Mac?

Well, Apple doesn't want you to (with good reason, automounter owns this dir, which makes it easier to do NFS mounts and such) so you shouldn't muck with it but if you really just 'have to do it', here is how you can.

Basically: Edit `/etc/auto_master` and remove or comment out the line that starts with "/home".

<!-- more -->

example:

    sudo vim /etc/auto_master

before:

    # Automounter master map
    +auto_master            # Use directory service
    /net                    -hosts          -nobrowse,hidefromfinder,nosuid
    /home                  auto_home      -nobrowse,hidefromfinder
    /Network/Servers        -fstab
    /-                      -static



after:


    # Automounter master map
    +auto_master            # Use directory service
    /net                    -hosts          -nobrowse,hidefromfinder,nosuid
    #/home                  auto_home      -nobrowse,hidefromfinder
    /Network/Servers        -fstab
    /-                      -static



to have the change take effect without a reboot:

    sudo automount

.

    mkdir /home/test
    ls -l /home/
    total 0
    drwxr-xr-x 3 root admin 102 Aug 10 11:33 test

NOTE: I wouldn't do anything 'important' with this directory as it's easy to forget you altered this and an upgrade will plow over this directory, removing all data. (this dir is also not included in any Time Machine backups.